name: Label PRs
permissions:
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened, converted_to_draft, ready_for_review, labeled, unlabeled]
  pull_request_review:
    types: [submitted]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(github.event)
            console.log(context)
  opened:
    if: (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review') && github.event.pull_request.state == 'open' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs-review"]
            })
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["in-progress"]
              })
            } catch(err) {
              console.log(err)
              if (!(err.name === "HttpError" && err.status === 404)) {
                console.log("404")
                throw new err
              }
            }
  draft:
    if: (github.event.action == 'opened' || github.event.action == 'converted_to_draft') && github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["in-progress"]
            })
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["needs-review"]
            })
  approved:
    if: github.event.action == 'submitted' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ready-to-merge"]
            })
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["needs-review"]
            })
  ready:
    if: github.event.action == 'labeled' || github.event.action == 'unlabeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.issue)
            console.log(await github.rest.pulls.get({...context.issue, pull_number: context.issue.number}))
